---
title: "Test"
author: "Geoffroy Gagliardi"
date: "08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pgks}
library(modelr)
library(tidyverse)
library(mmr)

theme_set(theme_bw())
```

```{r import}
df.mmr <- read.csv("../data/testadni.csv", sep=";")
```

# Before Use

# Wrangle

## Demographics

```{r rename_demogs}
df.mmr <- df.mmr %>%
  rename(ID = X, 
         Gender = PTGENDER,
         Education = PTEDUCAT, 
         Age = AGE)
```


## Vectors

```{r vectors}
demographics <- c("ID", "Gender", "Education", "Age")
markers <- c("AV45", "FDG")
complaint <- c("EcogPtMem")
memory <- c("RAVLT.immediate", "RAVLT.learning",
            "RAVLT.forgetting", "RAVLT.perc.forgetting",
            "ADASQ4", "LDELTOTAL")
```

## Distribution

```{r check_dist}
df.mmr %>% select(complaint, memory) %>%
  gather(key = "Measure", value = "Score", c(complaint, memory)) %>%
  ggplot(aes(x = Score)) + geom_histogram(binwidth = 0.1) +
  facet_wrap(~ Measure, scales = 'free')
```

```{r def_dist}
linear <- c("EcogPtMem", "RAVLT.immediate", "RAVLT.forgetting", "RAVLT.perc.forgetting", "ADASQ4")
binomial <- tibble(tests = c("RAVLT.learning", "LDELTOTAL"), # Measures that will be considered as binomial
                   max = c(75, 25)) # Max scores of above measures (in the same order)
```


```{r mmr_build}
df.mmr <- mmr_build(mem = memory,
                    comp = complaint,
                    vect.linear = linear,
                    vect.binomial = binomial,
                    df = df.mmr)
```

```{r mmr_min}
df.mmr %>% select(demographics, markers, Memory, Complaint, MMR, ACDC)
```

```{r mmr_save}
# df.mmr %>% select(demographics, markers, Memory, Complaint, MMR, ACDC) %>%
#   write.csv2(x = ., file = "path.csv")
```

